manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: oleksandrmaslov
      url-base: https://github.com/oleksandrmaslov
    - name: kumamuk-git
      url-base: https://github.com/kumamuk-git
  projects:
    - name: zmk-pointing-acceleration
      remote: oleksandrmaslov
      revision: main
      
    - name: zmk
      remote: zmkfirmware
      revision: v0.2
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: kumamuk-git
      revision: main
  self:
    path: config
